// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT_TesteGeral', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT_TesteGeral', async function() {
    // Test name: CT_TesteGeral
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://cadastrocars.vercel.app/")
    // 2 | setWindowSize | 1347x731 | 
    await driver.manage().window().setRect({ width: 1347, height: 731 })
    // 3 | click | linkText=Cadastrar | 
    await driver.findElement(By.linkText("Cadastrar")).click()
    // 4 | click | css=.brandField | 
    await driver.findElement(By.css(".brandField")).click()
    // 5 | select | css=.brandField | label=Volkswagen
    {
      const dropdown = await driver.findElement(By.css(".brandField"))
      await dropdown.findElement(By.xpath("//option[. = 'Volkswagen']")).click()
    }
    // 6 | click | css=.modelField | 
    await driver.findElement(By.css(".modelField")).click()
    // 7 | type | css=.modelField | Fox 1.0
    await driver.findElement(By.css(".modelField")).sendKeys("Fox 1.0")
    // 8 | click | css=.yearField | 
    await driver.findElement(By.css(".yearField")).click()
    // 9 | type | css=.yearField | 2010
    await driver.findElement(By.css(".yearField")).sendKeys("2010")
    // 10 | click | css=.kmField | 
    await driver.findElement(By.css(".kmField")).click()
    // 11 | type | css=.kmField | 0
    await driver.findElement(By.css(".kmField")).sendKeys("0")
    // 12 | click | css=.priceField | 
    await driver.findElement(By.css(".priceField")).click()
    // 13 | type | css=.priceField | 38000.00
    await driver.findElement(By.css(".priceField")).sendKeys("38000.00")
    // 14 | click | css=.full | 
    await driver.findElement(By.css(".full")).click()
    // 15 | click | css=.carItem:nth-child(6) .pointButton | 
    await driver.findElement(By.css(".carItem:nth-child(6) .pointButton")).click()
    // 16 | click | css=.pointWindowBtn:nth-child(1) | 
    await driver.findElement(By.css(".pointWindowBtn:nth-child(1)")).click()
    // 17 | click | css=.modelField | 
    await driver.findElement(By.css(".modelField")).click()
    // 18 | type | css=.modelField | Fox 1.4
    await driver.findElement(By.css(".modelField")).sendKeys("Fox 1.4")
    // 19 | click | css=.yearField | 
    await driver.findElement(By.css(".yearField")).click()
    // 20 | type | css=.yearField | 2012
    await driver.findElement(By.css(".yearField")).sendKeys("2012")
    // 21 | click | css=.kmField | 
    await driver.findElement(By.css(".kmField")).click()
    // 22 | type | css=.kmField | 50
    await driver.findElement(By.css(".kmField")).sendKeys("50")
    // 23 | click | css=.priceField | 
    await driver.findElement(By.css(".priceField")).click()
    // 24 | type | css=.priceField | 51000.00
    await driver.findElement(By.css(".priceField")).sendKeys("51000.00")
    // 25 | click | css=.full | 
    await driver.findElement(By.css(".full")).click()
    // 26 | click | css=.carItem:nth-child(6) .pointButton | 
    await driver.findElement(By.css(".carItem:nth-child(6) .pointButton")).click()
    // 28 | click | css=.pointWindowBtn:nth-child(2) | 
    await driver.findElement(By.css(".pointWindowBtn:nth-child(2)")).click()
    // 29 | assertConfirmation | Tem certeza que deseja excluir? | 
    assert(await driver.switchTo().alert().getText() == "Tem certeza que deseja excluir?")
    // 30 | webdriverChooseOkOnVisibleConfirmation |  | 
    await driver.switchTo().alert().accept()
  })
})
